// This file is automatically generated by the release process
// Do not modify manually
import pkg from '../../package.json';

export const version = pkg.version;
export const versionDate = new Date().toISOString().split('T')[0];