// This file is automatically generated by the release process
// Do not modify manually

// Hard-code the current version until the CI process updates it
export const version = '0.1.0';
export const versionDate = new Date().toISOString().split('T')[0];

// The version will be updated by the GitHub Actions workflow when commits are pushed to main/master