// This script updates the version.ts file with the current version from package.json
const fs = require('fs');
const path = require('path');

// Read the current version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Update the version.ts file
const versionFilePath = path.join(__dirname, '..', 'client', 'src', 'version.ts');
const content = `// This file is automatically generated by the release process
// Do not modify manually

// Current version from package.json
export const version = '${version}';
export const versionDate = new Date().toISOString().split('T')[0];
`;

// Write the updated file
fs.writeFileSync(versionFilePath, content, 'utf8');

console.log(`Updated client/src/version.ts with version ${version}`);